# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testlink-Api-Facade-Workflow

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Static Analysis
        run: yarn lint && yarn style:check

      - name: Run unit tests
        run: yarn test:unit

      - name: Run Coverage
        run: yarn global add codecov && codecov --disable=gcov --token="$CODECOV_TOKEN"
